# Numpy for Machine Learning

Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.

<b>Numpy vs Python Lists:</b>

- The list can be homogeneous or heterogeneous.
- Element wise operation is not possible on the list.
- Python list is by default 4 dimensional. But we can create an N-dimensional list. But then too it will be 4 D list storing another 4D list.
- Element of a list need not be contiguous in memory.

<b> Numpy</b>
- Consume less memory.
- Fast when compared to the python list.
- Convenient to use.

In [4]:
#!pip install numpy     # To install in your current environment
import numpy as np

In [3]:
np.__version__ #  To confirm current installed version

'1.26.3'

In [5]:
x= np.random.randint(10,size=(3,4,5)) #Generate random dataset to work with
x

array([[[1, 9, 7, 5, 4],
        [0, 0, 1, 6, 9],
        [5, 7, 3, 4, 7],
        [3, 2, 8, 5, 1]],

       [[3, 4, 7, 5, 5],
        [2, 5, 3, 0, 9],
        [2, 4, 0, 9, 6],
        [1, 1, 4, 1, 9]],

       [[1, 8, 0, 5, 2],
        [5, 0, 3, 3, 3],
        [6, 9, 8, 2, 0],
        [7, 1, 4, 9, 3]]])

In [6]:
#ndim
x.ndim

3

In [8]:
x.shape

(3, 4, 5)

In [9]:
x.size

60

In [10]:
# Data type
x.dtype

dtype('int64')

In [11]:
# Itemsize list the size of each array element
x.itemsize #8 bytes

8

In [12]:
#nbyte total size of array object
x.nbytes #8*60=480 bytes

480

### Creating Arrays

In [13]:
x = np.array(object=[1,2,3,4,5])

In [14]:
type(x)

numpy.ndarray

In [15]:
x.dtype

dtype('int64')

In [16]:
x = np.array(object=[1,2,3,4,5], dtype = complex)

In [17]:
x

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j])

In [18]:
y = np.array((1,2,3,4,5))
type(y)

numpy.ndarray

## Create Array From Scratch

In [21]:
np.zeros((4,5), dtype=int) # Create arrays filled with zeros

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [22]:
np.ones((3,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [23]:
np.full(shape=(4,4), fill_value=5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])