In [ ]:
Day- of #30daysofpython
Topic: Numpy part-2
Indexing 1-D arrays
Indexing Multi-Dimensional arrays
Indexing 1-D arrays
In [2]:
import numpy as np
a = np.arange(1,11)
print(a)
[ 1  2  3  4  5  6  7  8  9 10]
In [7]:
print(a[0])
print(a[[0,3,6]])  # Prints '0th','3rd''6th' index elements
print(a[0:])
print(a[:3])
print(a[0:10:2])
print(a[0::2])
print(a[0:10:3])
1
[1 4 7]
[ 1  2  3  4  5  6  7  8  9 10]
[1 2 3]
[1 3 5 7 9]
[1 3 5 7 9]
[ 1  4  7 10]
Indexing Multi-Dimensional arrays
1342893-2_d_array.png

In [8]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
In [13]:
print(a[0])
[1 2 3]
In [14]:
print(a[0:])
[[1 2 3]
 [4 5 6]
 [7 8 9]]
In [15]:
print(a[:])
[[1 2 3]
 [4 5 6]
 [7 8 9]]
In [16]:
print(a[0,])
[1 2 3]
In [17]:
print(a[1,])
[4 5 6]
In [18]:
print(a[2,])
[7 8 9]
In [19]:
print(a[0,0])
print(a[0,1])
print(a[0,2])
1
2
3
In [22]:
print(a[0,0])
print(a[1,0])
print(a[2,0])
1
4
7
In [21]:
print(a[0,0])
print(a[1,1])
print(a[2,2])
1
5
9
In [23]:
print(a[0,:]) #Prints 0th row, all columns
[1 2 3]
In [25]:
print(a[:,2]) #Prints every row, 2nd column
[3 6 9]
In [26]:
print(a[1:3,1:3])
[[5 6]
 [8 9]]
In [ ]: